### ISSUE TITLE
Problems with ipaddress

### ISSUE THREAD

**Issue by thusser** [jdswinbank/Comet#38]
After first installing comet, running "trial comet" gave me lots of error messages like this (running in Python 2.7.10 on Ubuntu 15.10):

exceptions.ValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network

Updating ipaddress via pip from 1.0.14 (which is in the Ubuntu 15.10 package) to 1.0.16 helped a little, now the message changed to:

ipaddress.AddressValueError: '127.0.0.1/32' does not appear to be an IPv4 or IPv6 network. Did you pass in a bytes (str in Python 2) instead of a unicode object?

So the call to ip_network should be ip_network(u'127.0.0.1/32') instead of ip_network('127.0.0.1/32'). 
Is this only a problem for me or am I doing something wrong?

**Comment by jdswinbank** [comment]
I suspect the issue here is just confusion over exactly which module to use. Unfortunately, [ipaddress](https://github.com/phihag/ipaddress) and [py2-ipaddress](https://bitbucket.org/kwi/py2-ipaddress/) have very similar names and functionality. Comet uses the latter: that's what you'll get if you follow the link in the README or `pip install -r requirements.txt`, but I bet your Ubuntu system has the former packaged, and they aren't compatible.

Does that resolve the issue?

**Comment by thusser** [comment]
Yep, that worked. I also had to install lxml from the Ubuntu repo and not using pip, but now everything seems fine. Thanks for the quick help.
